#!/bin/bash
# Preserve-versus-remove cross-cluster-edge ablation: 2 modes × 2 datasets × 7 models × 5 seeds.
SELECTED_GPUS="${SELECTED_GPUS:-0,1,2,3,4,5,6,7}"; MAX_PARALLEL="${MAX_PARALLEL:-0}"; PROCESSES_PER_GPU="${JOBS_PER_GPU:-1}"
RESUME="${RESUME:-true}"; STREAM_NUM_WORKERS="${STREAM_NUM_WORKERS:-8}"; MAX_EPOCHS="${MAX_EPOCHS:-300}"; MIN_EPOCHS="${MIN_EPOCHS:-1}"; CHECK_VAL_EVERY_N_EPOCH="${CHECK_VAL_EVERY_N_EPOCH:-5}"; EARLY_STOPPING_PATIENCE="${EARLY_STOPPING_PATIENCE:-5}"
DRY_RUN="${DRY_RUN:-false}"
wandb_entity="${wandb_entity:-topobench-scalability}"; WANDB_PROJECT_PREFIX="${WANDB_PROJECT_PREFIX:-ablation_cross_cluster_edges}"; DATASET_FILTER="${DATASET_FILTER:-}"; MODEL_FILTER="${MODEL_FILTER:-}"
if [[ -n "${DATA_SEEDS_OVERRIDE:-}" ]]; then read -ra DATA_SEEDS <<< "${DATA_SEEDS_OVERRIDE//,/ }"; else DATA_SEEDS=(0 1 2 3 4); fi
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"; script_name="$(basename "${BASH_SOURCE[0]}" .sh)"; log_group="${script_name}_sweep"; source "$SCRIPT_DIR/common.sh"
SPECS=(
"questions|graph/questions_for_partitioning|gcn|graph/gcn|graph|0.0001|0|128|0.2|500|20|0.2" "questions|graph/questions_for_partitioning|edgnn|hypergraph/edgnn|hypergraph|0.01|0.001|32|0.2|500|50|0.0" "questions|graph/questions_for_partitioning|unignn|hypergraph/unignn2|hypergraph|0.001|0.001|128|0.0|1000|40|" "questions|graph/questions_for_partitioning|cwn|cell/cwn|cell|0.01|0.001|32|0.3|1000|40|" "questions|graph/questions_for_partitioning|cell_topotune|cell/topotune|cell|0.01|0.001|128|0.3|500|50|0.2" "questions|graph/questions_for_partitioning|scn|simplicial/scn|simplicial|0.001|0.001|64|0.1|500|50|" "questions|graph/questions_for_partitioning|sccnn|simplicial/sccnn_custom|simplicial|0.001|1e-05|128|0.3|500|30|"
"amazon_ratings|graph/amazon_ratings_for_partitioning|gcn|graph/gcn|graph|0.01|0.0001|128|0.3|64|4|0.0" "amazon_ratings|graph/amazon_ratings_for_partitioning|edgnn|hypergraph/edgnn|hypergraph|0.001|0.0001|128|0.3|128|4|0.0" "amazon_ratings|graph/amazon_ratings_for_partitioning|unignn|hypergraph/unignn2|hypergraph|0.01|0.0001|64|0.0|32|8|" "amazon_ratings|graph/amazon_ratings_for_partitioning|cwn|cell/cwn|cell|0.01|0.001|128|0.2|64|16|" "amazon_ratings|graph/amazon_ratings_for_partitioning|cell_topotune|cell/topotune|cell|0.01|1e-05|128|0.0|32|8|0.5" "amazon_ratings|graph/amazon_ratings_for_partitioning|scn|simplicial/scn|simplicial|0.001|0|128|0.2|32|8|" "amazon_ratings|graph/amazon_ratings_for_partitioning|sccnn|simplicial/sccnn_custom|simplicial|0.001|0.001|128|0.2|32|4|"
)
match(){ [[ -z "$2" || ",$2," == *",$1,"* ]]; }
add_transform(){ case "$1" in hypergraph) cmd+=("transforms=liftings/graph2hypergraph_default" "transforms/liftings/graph2hypergraph@transforms.graph2hypergraph_lifting=khop_large_scale");; cell) cmd+=("transforms=liftings/graph2cell_default" "transforms/liftings/graph2cell@transforms.graph2cell_lifting=cycle_selective");; simplicial) cmd+=("transforms=liftings/graph2simplicial_default" "transforms/liftings/graph2simplicial@transforms.graph2simplicial_lifting=clique_selective");; esac; }
run(){ init_experiment_environment; detect_gpu_slots; [[ "$PROCESSES_PER_GPU" =~ ^[1-9][0-9]*$ ]] || exit 1; local originals=("${gpus[@]}") expanded=() gpu i; for gpu in "${originals[@]}"; do for ((i=1;i<=PROCESSES_PER_GPU;i++)); do expanded+=("$gpu"); done; done; gpus=("${expanded[@]}"); [[ "$MAX_PARALLEL" == 0 || "$MAX_PARALLEL" -ge ${#gpus[@]} ]] || gpus=("${gpus[@]:0:MAX_PARALLEL}"); slot_pids=(); for i in "${!gpus[@]}"; do slot_pids[$i]=0; done
local success="$LOG_DIR/$log_group/SUCCESSFUL_RUNS.log" spec d conf m model kind lr wd ch pd parts q drop edge seed slot name cmdstr
for spec in "${SPECS[@]}"; do IFS='|' read -r d conf m model kind lr wd ch pd parts q drop <<< "$spec"; match "$d" "$DATASET_FILTER" && match "$m" "$MODEL_FILTER" || continue; for edge in true false; do for seed in "${DATA_SEEDS[@]}"; do name="cross_edges_$([[ "$edge" == true ]] && echo preserve || echo remove)_${d}_${m}_seed${seed}"; [[ "$RESUME" == true && -f "$success" ]] && grep -Fq "[SUCCESS] ${name}" "$success" && continue; slot=-1; while [[ $slot -lt 0 ]]; do for i in "${!gpus[@]}"; do [[ ${slot_pids[$i]} -eq 0 ]] || ! kill -0 "${slot_pids[$i]}" 2>/dev/null && { slot=$i; break; }; done; [[ $slot -lt 0 ]] && wait -n; done
cmd=(python -m topobench "dataset=$conf" "model=$model" trainer=gpu logger=wandb "optimizer.parameters.lr=$lr" "optimizer.parameters.weight_decay=$wd" "model.feature_encoder.out_channels=$ch" "model.feature_encoder.proj_dropout=$pd" "dataset.dataloader_params.batch_size=1" "dataset.split_params.data_seed=$seed" "seed=$seed" "dataset.loader.parameters.cluster.num_parts=$parts" "dataset.loader.parameters.stream.q=$q" "++dataset.loader.parameters.stream.q_val=$q" "++dataset.loader.parameters.stream.q_test=$q" "++dataset.loader.parameters.stream.reconstruct_cross_cluster_edges=$edge" "dataset.loader.parameters.stream.num_workers=$STREAM_NUM_WORKERS" "dataset.dataloader_params.num_workers=$STREAM_NUM_WORKERS" "trainer.max_epochs=$MAX_EPOCHS" "trainer.min_epochs=$MIN_EPOCHS" "trainer.check_val_every_n_epoch=$CHECK_VAL_EVERY_N_EPOCH" "callbacks.early_stopping.patience=$EARLY_STOPPING_PATIENCE" "trainer.devices=[${gpus[$slot]}]" "logger.wandb.project=${WANDB_PROJECT_PREFIX}_${d}" "+logger.wandb.name=$name" +trainer.enable_progress_bar=false); [[ -n "$wandb_entity" ]] && cmd+=("+logger.wandb.entity=$wandb_entity"); [[ "$m" == gcn || "$m" == edgnn ]] && cmd+=("model.backbone.dropout=$drop"); [[ "$m" == cell_topotune ]] && cmd+=("model.backbone.GNN.dropout=$drop"); add_transform "$kind"; printf -v cmdstr '%q ' "${cmd[@]}"; if [[ "$DRY_RUN" == true ]]; then printf '[DRY_RUN] %s\n' "$cmdstr"; slot_pids[$slot]=0; else run_and_log "$cmdstr" "$log_group" "$name" "$LOG_DIR" & slot_pids[$slot]=$!; fi; done; done; done; [[ "$DRY_RUN" == true ]] || wait; }
run
