#!/bin/bash
# Fixed versus reshuffled cluster groups: two datasets, seven models, five seeds.
SELECTED_GPUS="${SELECTED_GPUS:-0}"; PROCESSES_PER_GPU="${JOBS_PER_GPU:-1}"; MAX_PARALLEL="${MAX_PARALLEL:-0}"; RESUME="${RESUME:-true}"; DRY_RUN="${DRY_RUN:-false}"
DATASET_FILTER="${DATASET_FILTER:-}"; MODEL_FILTER="${MODEL_FILTER:-}"; WANDB_PROJECT_PREFIX="${WANDB_PROJECT_PREFIX:-ablation_cluster_shuffling}"; wandb_entity="${wandb_entity:-topobench-scalability}"
if [[ -n "${DATA_SEEDS_OVERRIDE:-}" ]]; then read -ra DATA_SEEDS <<< "${DATA_SEEDS_OVERRIDE//,/ }"; else DATA_SEEDS=(0 1 2 3 4); fi
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; log_group="ablation_cluster_shuffling_sweep"; source "$SCRIPT_DIR/common.sh"
# dataset|config|model|transform|parts|q
SPECS=(
"questions|graph/questions_for_partitioning|gcn|graph|500|20" "questions|graph/questions_for_partitioning|edgnn|hypergraph|500|50" "questions|graph/questions_for_partitioning|unignn2|hypergraph|1000|40" "questions|graph/questions_for_partitioning|cwn|cell|1000|40" "questions|graph/questions_for_partitioning|topotune|cell|500|50" "questions|graph/questions_for_partitioning|scn|simplicial|500|50" "questions|graph/questions_for_partitioning|sccnn_custom|simplicial|500|30"
"amazon_ratings|graph/amazon_ratings_for_partitioning|gcn|graph|64|4" "amazon_ratings|graph/amazon_ratings_for_partitioning|edgnn|hypergraph|128|4" "amazon_ratings|graph/amazon_ratings_for_partitioning|unignn2|hypergraph|32|8" "amazon_ratings|graph/amazon_ratings_for_partitioning|cwn|cell|64|16" "amazon_ratings|graph/amazon_ratings_for_partitioning|topotune|cell|32|8" "amazon_ratings|graph/amazon_ratings_for_partitioning|scn|simplicial|32|8" "amazon_ratings|graph/amazon_ratings_for_partitioning|sccnn_custom|simplicial|32|4")
match(){ [[ -z "$2" || ",$2," == *",$1,"* ]]; }
transform(){ case "$1" in hypergraph) cmd+=("transforms=liftings/graph2hypergraph_default" "transforms/liftings/graph2hypergraph@transforms.graph2hypergraph_lifting=khop_large_scale");; cell) cmd+=("transforms=liftings/graph2cell_default" "transforms/liftings/graph2cell@transforms.graph2cell_lifting=cycle_selective");; simplicial) cmd+=("transforms=liftings/graph2simplicial_default" "transforms/liftings/graph2simplicial@transforms.graph2simplicial_lifting=clique_selective");; esac; }
run(){ init_experiment_environment; detect_gpu_slots; [[ "$PROCESSES_PER_GPU" =~ ^[1-9][0-9]*$ ]] || { echo "ERROR: JOBS_PER_GPU must be positive." >&2; exit 1; }; local base=("${gpus[@]}") exp=() g i; for g in "${base[@]}"; do for ((i=1;i<=PROCESSES_PER_GPU;i++)); do exp+=("$g"); done; done; gpus=("${exp[@]}"); [[ "$MAX_PARALLEL" == 0 || "$MAX_PARALLEL" -ge ${#gpus[@]} ]] || gpus=("${gpus[@]:0:MAX_PARALLEL}"); slot_pids=(); for i in "${!gpus[@]}"; do slot_pids[$i]=0; done; echo "Maximum concurrent runs: ${#gpus[@]}"; local success="$LOG_DIR/$log_group/SUCCESSFUL_RUNS.log" s d cfg model kind parts q shuffle seed slot name cmdstr
for s in "${SPECS[@]}"; do IFS='|' read -r d cfg model kind parts q <<< "$s"; match "$d" "$DATASET_FILTER" && match "${model/topotune/cell_topotune}" "$MODEL_FILTER" || continue; for shuffle in true false; do for seed in "${DATA_SEEDS[@]}"; do name="cluster_shuffling_$([[ "$shuffle" == true ]] && echo reshuffle || echo fixed)_${d}_${model}_seed${seed}"; [[ "$RESUME" == true && -f "$success" ]] && grep -Fq "[SUCCESS] ${name}" "$success" && continue; slot=-1; while [[ $slot -lt 0 ]]; do for i in "${!gpus[@]}"; do if [[ ${slot_pids[$i]} -eq 0 ]] || ! kill -0 "${slot_pids[$i]}" 2>/dev/null; then slot=$i; break; fi; done; [[ $slot -lt 0 ]] && wait -n; done
cmd=(python -m topobench "dataset=$cfg" "model=$([[ "$model" == topotune ]] && echo cell/topotune || echo ${kind}/${model})" trainer=gpu logger=wandb "dataset.split_params.data_seed=$seed" "seed=$seed" "dataset.loader.parameters.cluster.num_parts=$parts" "dataset.loader.parameters.stream.q=$q" "++dataset.loader.parameters.stream.q_val=$q" "++dataset.loader.parameters.stream.q_test=$q" "++dataset.loader.parameters.stream.train_shuffle=$shuffle" "trainer.devices=[${gpus[$slot]}]" "logger.wandb.project=${WANDB_PROJECT_PREFIX}_${d}" "+logger.wandb.name=$name" +trainer.enable_progress_bar=false); transform "$kind"; [[ -n "$wandb_entity" ]] && cmd+=("+logger.wandb.entity=$wandb_entity"); printf -v cmdstr '%q ' "${cmd[@]}"; if [[ "$DRY_RUN" == true ]]; then printf '[DRY_RUN] %s\n' "$cmdstr"; slot_pids[$slot]=0; else run_and_log "$cmdstr" "$log_group" "$name" "$LOG_DIR" & slot_pids[$slot]=$!; fi; done; done; done; [[ "$DRY_RUN" == true ]] || wait; }
run
